// Generated by tools/build-manifest.ps1 - do not edit by hand; re-run the script instead.
window.MAJOR_ITEMS = [
    {
        "num":  "0",
        "word":  "Zoo",
        "src":  "images/0-Zoo.jpg"
    },
    {
        "num":  "1",
        "word":  "Tea",
        "src":  "images/1-Tea.jpg"
    },
    {
        "num":  "2",
        "word":  "Knee",
        "src":  "images/2-Knee.jpg"
    },
    {
        "num":  "3",
        "word":  "Moe",
        "src":  "images/3-Moe.jpg"
    },
    {
        "num":  "4",
        "word":  "Ra",
        "src":  "images/4-Ra.jpg"
    },
    {
        "num":  "5",
        "word":  "Eel",
        "src":  "images/5-Eel.jpg"
    },
    {
        "num":  "6",
        "word":  "Shoe",
        "src":  "images/6-Shoe.jpg"
    },
    {
        "num":  "7",
        "word":  "Key",
        "src":  "images/7-Key.jpg"
    },
    {
        "num":  "8",
        "word":  "Ivy",
        "src":  "images/8-Ivy.jpg"
    },
    {
        "num":  "9",
        "word":  "Bee",
        "src":  "images/9-Bee.jpg"
    },
    {
        "num":  "00",
        "word":  "Sauce",
        "src":  "images/00-Sauce.jpg"
    },
    {
        "num":  "01",
        "word":  "Suit",
        "src":  "images/01-Suit.jpg"
    },
    {
        "num":  "02",
        "word":  "Sun",
        "src":  "images/02-Sun.jpg"
    },
    {
        "num":  "03",
        "word":  "SIM",
        "src":  "images/03-SIM.jpg"
    },
    {
        "num":  "04",
        "word":  "Zara",
        "src":  "images/04-Zara.jpg"
    },
    {
        "num":  "05",
        "word":  "SEAL",
        "src":  "images/05-SEAL.jpg"
    },
    {
        "num":  "06",
        "word":  "Sash",
        "src":  "images/06-Sash.jpg"
    },
    {
        "num":  "07",
        "word":  "Sock",
        "src":  "images/07-Sock.jpg"
    },
    {
        "num":  "08",
        "word":  "Sofa",
        "src":  "images/08-Sofa.jpg"
    },
    {
        "num":  "09",
        "word":  "Soap",
        "src":  "images/09-Soap.jpg"
    },
    {
        "num":  "10",
        "word":  "Toes",
        "src":  "images/10-Toes.jpg"
    },
    {
        "num":  "11",
        "word":  "Tit",
        "src":  "images/11-Tit.jpg"
    },
    {
        "num":  "12",
        "word":  "Tan",
        "src":  "images/12-Tan.jpg"
    },
    {
        "num":  "13",
        "word":  "Team",
        "src":  "images/13-Team.jpg"
    },
    {
        "num":  "14",
        "word":  "Tear",
        "src":  "images/14-Tear.jpg"
    },
    {
        "num":  "15",
        "word":  "Tile",
        "src":  "images/15-Tile.jpg"
    },
    {
        "num":  "16",
        "word":  "Dish",
        "src":  "images/16-Dish.jpg"
    },
    {
        "num":  "17",
        "word":  "Duck",
        "src":  "images/17-Duck.jpg"
    },
    {
        "num":  "18",
        "word":  "Dove",
        "src":  "images/18-Dove.jpg"
    },
    {
        "num":  "19",
        "word":  "Tip",
        "src":  "images/19-Tip.jpg"
    },
    {
        "num":  "20",
        "word":  "Nose",
        "src":  "images/20-Nose.jpg"
    },
    {
        "num":  "21",
        "word":  "Net",
        "src":  "images/21-Net.jpg"
    },
    {
        "num":  "22",
        "word":  "Nun",
        "src":  "images/22-Nun.jpg"
    },
    {
        "num":  "23",
        "word":  "Gnome",
        "src":  "images/23-Gnome.jpg"
    },
    {
        "num":  "24",
        "word":  "Nori",
        "src":  "images/24-Nori.jpg"
    },
    {
        "num":  "25",
        "word":  "Nail",
        "src":  "images/25-Nail.jpg"
    },
    {
        "num":  "26",
        "word":  "Niche",
        "src":  "images/26-Niche.jpg"
    },
    {
        "num":  "27",
        "word":  "Nick",
        "src":  "images/27-Nick.jpg"
    },
    {
        "num":  "28",
        "word":  "Knife",
        "src":  "images/28-Knife.jpg"
    },
    {
        "num":  "29",
        "word":  "Nib",
        "src":  "images/29-Nib.jpg"
    },
    {
        "num":  "30",
        "word":  "Mouse",
        "src":  "images/30-Mouse.jpg"
    },
    {
        "num":  "31",
        "word":  "Mitt",
        "src":  "images/31-Mitt.jpg"
    },
    {
        "num":  "32",
        "word":  "Moon",
        "src":  "images/32-Moon.jpg"
    },
    {
        "num":  "33",
        "word":  "Mummy",
        "src":  "images/33-Mummy.jpg"
    },
    {
        "num":  "34",
        "word":  "Mare",
        "src":  "images/34-Mare.jpg"
    },
    {
        "num":  "35",
        "word":  "Mole",
        "src":  "images/35-Mole.jpg"
    },
    {
        "num":  "36",
        "word":  "Match",
        "src":  "images/36-Match.jpg"
    },
    {
        "num":  "37",
        "word":  "Mic",
        "src":  "images/37-Mic.jpg"
    },
    {
        "num":  "38",
        "word":  "Movie",
        "src":  "images/38-Movie.jpg"
    },
    {
        "num":  "39",
        "word":  "Map",
        "src":  "images/39-Map.jpg"
    },
    {
        "num":  "40",
        "word":  "Rose",
        "src":  "images/40-Rose.jpg"
    },
    {
        "num":  "41",
        "word":  "Root",
        "src":  "images/41-Root.jpg"
    },
    {
        "num":  "42",
        "word":  "Rain",
        "src":  "images/42-Rain.jpg"
    },
    {
        "num":  "43",
        "word":  "Room",
        "src":  "images/43-Room.jpg"
    },
    {
        "num":  "44",
        "word":  "Roar",
        "src":  "images/44-Roar.jpg"
    },
    {
        "num":  "45",
        "word":  "Rail",
        "src":  "images/45-Rail.jpg"
    },
    {
        "num":  "46",
        "word":  "Rash",
        "src":  "images/46-Rash.jpg"
    },
    {
        "num":  "47",
        "word":  "Rake",
        "src":  "images/47-Rake.jpg"
    },
    {
        "num":  "48",
        "word":  "Roof",
        "src":  "images/48-Roof.jpg"
    },
    {
        "num":  "49",
        "word":  "Rope",
        "src":  "images/49-Rope.jpg"
    },
    {
        "num":  "50",
        "word":  "Lace",
        "src":  "images/50-Lace.jpg"
    },
    {
        "num":  "51",
        "word":  "Lid",
        "src":  "images/51-Lid.jpg"
    },
    {
        "num":  "52",
        "word":  "Lane",
        "src":  "images/52-Lane.jpg"
    },
    {
        "num":  "53",
        "word":  "Lime",
        "src":  "images/53-Lime.jpg"
    },
    {
        "num":  "54",
        "word":  "Lure",
        "src":  "images/54-Lure.jpg"
    },
    {
        "num":  "55",
        "word":  "Lilly",
        "src":  "images/55-Lilly.jpg"
    },
    {
        "num":  "56",
        "word":  "Leash",
        "src":  "images/56-Leash.jpg"
    },
    {
        "num":  "57",
        "word":  "Leek",
        "src":  "images/57-Leek.jpg"
    },
    {
        "num":  "58",
        "word":  "Loofah",
        "src":  "images/58-Loofah.jpg"
    },
    {
        "num":  "59",
        "word":  "Lab",
        "src":  "images/59-Lab.jpg"
    },
    {
        "num":  "60",
        "word":  "Cheese",
        "src":  "images/60-Cheese.jpg"
    },
    {
        "num":  "61",
        "word":  "Cheetah",
        "src":  "images/61-Cheetah.jpg"
    },
    {
        "num":  "62",
        "word":  "Chain",
        "src":  "images/62-Chain.jpg"
    },
    {
        "num":  "63",
        "word":  "Gym",
        "src":  "images/63-Gym.jpg"
    },
    {
        "num":  "64",
        "word":  "Chair",
        "src":  "images/64-Chair.jpg"
    },
    {
        "num":  "65",
        "word":  "Jail",
        "src":  "images/65-Jail.jpg"
    },
    {
        "num":  "66",
        "word":  "Judge",
        "src":  "images/66-Judge.jpg"
    },
    {
        "num":  "67",
        "word":  "Check",
        "src":  "images/67-Check.jpg"
    },
    {
        "num":  "68",
        "word":  "Chef",
        "src":  "images/68-Chef.jpg"
    },
    {
        "num":  "69",
        "word":  "Chip",
        "src":  "images/69-Chip.jpg"
    },
    {
        "num":  "70",
        "word":  "Casio",
        "src":  "images/70-Casio.jpg"
    },
    {
        "num":  "71",
        "word":  "Cat",
        "src":  "images/71-Cat.jpg"
    },
    {
        "num":  "72",
        "word":  "Cone",
        "src":  "images/72-Cone.jpg"
    },
    {
        "num":  "73",
        "word":  "Kimi",
        "src":  "images/73-Kimi.jpg"
    },
    {
        "num":  "74",
        "word":  "Car",
        "src":  "images/74-Car.jpg"
    },
    {
        "num":  "75",
        "word":  "Coal",
        "src":  "images/75-Coal.jpg"
    },
    {
        "num":  "76",
        "word":  "Cash",
        "src":  "images/76-Cash.jpg"
    },
    {
        "num":  "77",
        "word":  "Kick",
        "src":  "images/77-Kick.jpg"
    },
    {
        "num":  "78",
        "word":  "Cough",
        "src":  "images/78-Cough.jpg"
    },
    {
        "num":  "79",
        "word":  "Cup",
        "src":  "images/79-Cup.jpg"
    },
    {
        "num":  "80",
        "word":  "Fuzz",
        "src":  "images/80-Fuzz.jpg"
    },
    {
        "num":  "81",
        "word":  "Photo",
        "src":  "images/81-Photo.jpg"
    },
    {
        "num":  "82",
        "word":  "Phone",
        "src":  "images/82-Phone.jpg"
    },
    {
        "num":  "83",
        "word":  "Foam",
        "src":  "images/83-Foam.jpg"
    },
    {
        "num":  "84",
        "word":  "Fur",
        "src":  "images/84-Fur.jpg"
    },
    {
        "num":  "85",
        "word":  "File",
        "src":  "images/85-File.jpg"
    },
    {
        "num":  "86",
        "word":  "Fish",
        "src":  "images/86-Fish.jpg"
    },
    {
        "num":  "87",
        "word":  "FAC",
        "src":  "images/87-FAC.jpg"
    },
    {
        "num":  "88",
        "word":  "FIFA",
        "src":  "images/88-FIFA.jpg"
    },
    {
        "num":  "89",
        "word":  "Fab 5",
        "src":  "images/89-Fab%205.jpg"
    },
    {
        "num":  "90",
        "word":  "Piss",
        "src":  "images/90-Piss.jpg"
    },
    {
        "num":  "91",
        "word":  "Bat",
        "src":  "images/91-Bat.jpg"
    },
    {
        "num":  "92",
        "word":  "Bane",
        "src":  "images/92-Bane.jpg"
    },
    {
        "num":  "93",
        "word":  "Bam Marguera",
        "src":  "images/93-Bam_Marguera.jpg"
    },
    {
        "num":  "94",
        "word":  "Bear",
        "src":  "images/94-Bear.jpg"
    },
    {
        "num":  "95",
        "word":  "Pill",
        "src":  "images/95-Pill.jpg"
    },
    {
        "num":  "96",
        "word":  "Peach",
        "src":  "images/96-Peach.jpg"
    },
    {
        "num":  "97",
        "word":  "Bike",
        "src":  "images/97-Bike.jpg"
    },
    {
        "num":  "98",
        "word":  "Beef",
        "src":  "images/98-Beef.jpg"
    },
    {
        "num":  "99",
        "word":  "Pope",
        "src":  "images/99-Pope.jpg"
    }
];
