<#
  Scans the images folder and writes manifest.js for the Major System Trainer.

  File naming:  <number>-<word>.<ext>
    00-sauce.jpg   07-sock.png   7-key.jpg   12-tin_can.webp
  - Two-digit numbers (00-99) and single-digit numbers (0-9) are separate entries.
  - The word is optional; "_" and "-" inside it become spaces.
  - Extensions: jpg, jpeg, png, webp, gif.

  Usage (from the project folder):
    powershell -ExecutionPolicy Bypass -File tools\build-manifest.ps1
#>
param(
  [string]$ImagesDir = (Join-Path $PSScriptRoot "..\images"),
  [string]$OutFile   = (Join-Path $PSScriptRoot "..\manifest.js"),
  [int]$MaxSizeKB    = 500
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path -LiteralPath $ImagesDir -PathType Container)) {
  Write-Host "Images folder not found: $ImagesDir" -ForegroundColor Red
  exit 1
}
$ImagesDir = (Resolve-Path -LiteralPath $ImagesDir).Path

$expected = @()
0..9  | ForEach-Object { $expected += "$_" }
0..99 | ForEach-Object { $expected += $_.ToString("00") }

$pattern = '^(\d{1,2})(?:\s*[-_ ]\s*(.+?))?\.(jpe?g|png|webp|gif)$'
$ignore  = @("thumbs.db", "desktop.ini")

$byNum    = @{}
$problems = 0
$warnings = 0

Get-ChildItem -LiteralPath $ImagesDir -File | Sort-Object Name | ForEach-Object {
  $name = $_.Name
  if ($name.StartsWith(".") -or $ignore -contains $name.ToLower()) { return }

  $m = [regex]::Match($name, $pattern, "IgnoreCase")
  if (-not $m.Success) {
    Write-Host "  BAD NAME   $name  (expected e.g. 07-sock.jpg)" -ForegroundColor Red
    $script:problems++
    return
  }

  $num  = $m.Groups[1].Value
  $word = ""
  if ($m.Groups[2].Success) { $word = ($m.Groups[2].Value -replace '[-_]+', ' ').Trim() }

  if ($byNum.ContainsKey($num)) {
    Write-Host "  DUPLICATE  $name  (number $num already used by $($byNum[$num].file); ignoring this one)" -ForegroundColor Red
    $script:problems++
    return
  }

  $sizeKB = [math]::Round($_.Length / 1KB)
  if ($sizeKB -gt $MaxSizeKB) {
    Write-Host "  LARGE      $name  ($sizeKB KB - consider resizing to ~800px wide for faster loading on phones)" -ForegroundColor Yellow
    $script:warnings++
  }

  $byNum[$num] = @{ file = $name; word = $word }
}

$missing = $expected | Where-Object { -not $byNum.ContainsKey($_) }
if ($missing) {
  Write-Host "  MISSING    $(@($missing).Count) number(s): $($missing -join ', ')" -ForegroundColor Yellow
  $warnings++
}

# Build entries in canonical order (0-9, then 00-99).
$entries = @()
foreach ($num in $expected) {
  if (-not $byNum.ContainsKey($num)) { continue }
  $e = $byNum[$num]
  $entries += [pscustomobject]@{
    num  = $num
    word = $e.word
    src  = "images/" + [uri]::EscapeDataString($e.file)
  }
}

$json = ConvertTo-Json -InputObject @($entries) -Depth 3
$content = "// Generated by tools/build-manifest.ps1 - do not edit by hand; re-run the script instead.`r`n" +
           "window.MAJOR_ITEMS = $json;`r`n"
[System.IO.File]::WriteAllText($OutFile, $content, (New-Object System.Text.UTF8Encoding($false)))

Write-Host ""
Write-Host "Wrote $($entries.Count) of $($expected.Count) images to $((Resolve-Path -LiteralPath $OutFile).Path)" -ForegroundColor Green
if ($problems -gt 0) { Write-Host "$problems problem(s) above need fixing." -ForegroundColor Red }
elseif ($warnings -gt 0) { Write-Host "Done, with warnings." -ForegroundColor Yellow }
else { Write-Host "All good." -ForegroundColor Green }
